### ISSUE TITLE
Grass fades out in a circle around player in eastern grassy fields

### ISSUE THREAD

**Issue by Snarfman** [Lyall/RF5Fix#1]
A particular type of grass in the eastern fields fades out in a circle around the player when you draw near. Grass in town is fine and the boosted LOD is great, but for some reason the grass in this region behaves oddly
![Rune Factory 5 2022-07-15 01-26-41](https://user-images.githubusercontent.com/109343766/179184831-d4920adc-ae02-44f1-8faa-f1f19b0137a0.png)
.

**Comment by Lyall** [comment]
Thanks for reporting this. Are you using the latest version (v0.0.3)? If so can you confirm that it goes away if IncreaseQuality is set to false in the config? That would help narrow down what's causing the issue.

**Comment by Snarfman** [comment]
When set to false the area of grass that displays is identical to the area of grass that is missing with it on. Very odd
![Rune Factory 5 2022-07-15 12-16-32](https://user-images.githubusercontent.com/109343766/179295953-8b802a9d-c1f4-406b-bb19-5419231215f1.png)
.

**Comment by Snarfman** [comment]
Its like some value is being inverted, for this type of grass alone (as far as I can tell so far). Hopefully you can figure it out, but if not the boosted LOD everywhere else is for sure worth putting up with this one problem.

Good hunting.

**Comment by Lyall** [comment]
This should be addressed in release v0.0.8 and onward. Users can adjust LOD Bias themselves in the config file.
