### ISSUE TITLE
Character 3D models in Friendship pane gone after v0.1.1 update

### ISSUE THREAD

**Issue by alliepet** [Lyall/RF5Fix#12]
Hello. After updating to 0.1.1 I noticed that characters are not showing their 3D model in the Friendship pane. When I press 3D View Mode they show up, but not in the main view.
![image](https://user-images.githubusercontent.com/72270749/184279933-1756a1bc-1db0-492e-bcd5-99d1ba2dcce1.png)
![image](https://user-images.githubusercontent.com/72270749/184279983-b2ab5414-a7a7-4335-a2b1-a66521d874aa.png)

**Comment by Lyall** [comment]
Yeah this one was my bad, I was updating the textures manually so I missed a few. I've made this automatic now in an update so it should address this issue. Give it a try in the [latest release](https://github.com/Lyall/RF5Fix/releases).

**Comment by alliepet** [comment]
Yes it works now!! Thank you so much!!
