### ISSUE TITLE
Monsters don't show up in naming menu anymore

### ISSUE THREAD

**Issue by kokoropaint** [Lyall/RF5Fix#13]
I think this is because of the HD portraits fix (I just updated to 0.1.2 and didn't check if this issue happened with 0.1.1) but when you tame a monster and the game goes to the menu to name it, the monster doesn't show up anymore. I've tried with 2 boss monsters and a Wooly and they all look like this:
![image](https://user-images.githubusercontent.com/37761120/184410626-1d2ed805-3aee-4c40-800c-ece710d6dd1c.png)

**Comment by Lyall** [comment]
Sorry this took so long, been very busy at the moment but this should be fixed in the latest release. That is unless there's more parts of the game where it has 3D previews but hopefully this is it!
