### ISSUE TITLE
Intro and logos no longer being skipped

### ISSUE THREAD

**Issue by alliepet** [Lyall/RF5Fix#15]
Booting up the game today and the intro/logos are no longer being skipped. My config has it set to "true" to skip. 
![image](https://user-images.githubusercontent.com/72270749/184524561-b791c157-fdf3-414f-9f43-405bd596102e.png)

Aug 12th it was working, though.

**Comment by Lyall** [comment]
That's odd as there was no changes to that part of the mod. Can you try deleting your configuration file and letting it generate a new one?

**Comment by alliepet** [comment]
Deleting the config file didn't fix it but reinstalling the mod did! I guess I should have tried that first haha, thank you!!

**Comment by alliepet** [comment]
Oh actually this is interesting - I reinstalled the mod and booted the game and the intros skipped, but then I closed it out and made some adjustments in the config file, saved it, and booted the game again and the intros are back (it seems like other parts of the mod aren't working either like the higher rez 3D models in the menus). All I changed in the config is the stuff under Graphic Tweaks and set them to the recommended quality setting.

**Comment by alliepet** [comment]
Okay restarting my computer fixed everything, it works perfectly now. How weird!! Sorry to waste your time thank youuu
