### ISSUE TITLE
Texture Replacement: PS button prompts?

### ISSUE THREAD

**Issue by GamerzHell9137** [Lyall/RF5Fix#16]
I know this is not an issue or a feature of the mod but is there a possibility to implement texture replacement so we can add PS button prompts? Weird that RF5 doesn't have them but RF4S did.

**Comment by Lyall** [comment]
So I've been look at this right now along with the Steam Deck controller bug and I've dumped the texture atlas for the controller icons and it does indeed have PlayStation button prompts. 

![sactx-1024x1024-DXT5-PadIconSpriteAtlas-52801ff0](https://user-images.githubusercontent.com/695941/184895277-53ed7d43-7027-491e-b519-d942f2aa1faf.png)

**Comment by BenjaminBrandtner** [comment]
I don't know if this is helpful: To my surprise my game was using Playstation button prompts from the beginning.

I'm using a "Thrustmaster ESWAP PRO for PS4 and PC" Controller and when I open the "Controller Configuration" from within the Steam Overlay it shows a picture of a PS4 controller.
So if Steam thinks that you're using a PS4 controller it seems the game will automatically use PS button prompts.

**Comment by Lyall** [comment]
> I don't know if this is helpful: To my surprise my game was using Playstation button prompts from the beginning.
> 
> I'm using a "Thrustmaster ESWAP PRO for PS4 and PC" Controller and when I open the "Controller Configuration" from within the Steam Overlay it shows a picture of a PS4 controller. So if Steam thinks that you're using a PS4 controller it seems the game will automatically use PS button prompts.

That's interesting, I tried spoofing the controller ID but it wasn't loading the appropriate button set. If you've actually seen PS4 prompts in game then I'll need to keep looking at this.

**Comment by Lyall** [comment]
Okay, I was able to change the controller type and yeah DS4 icons show up now. What's odd is that this should be happening correctly without the need of a mod. I wonder if Rune Factory 5 just has a messed up implementation of Steam Input. That might account for why the Steam Deck uses keyboard glyphs instead of generic gamepad ones.

![image](https://user-images.githubusercontent.com/695941/185173753-16298f49-07d2-4d21-828b-8d50089ae9b3.png)

**Comment by kokoropaint** [comment]
My DS4 has been recognized fine by RF5, I haven't had any issues since starting the game. I wonder why it's not working for some people.

**Comment by Lyall** [comment]
> My DS4 has been recognized fine by RF5, I haven't had any issues since starting the game. I wonder why it's not working for some people.

Yeah it's odd, as far as I can tell looking at the pseudocode I can access, it should be working fine. Regardless, I've added the option for controller icon overriding in the latest release (v0.1.4 as of this). Hopefully this will be of some use to those who aren't getting the correct controller icons.

**Comment by GamerzHell9137** [comment]
I think there are 2 reasons why people can't access it and those are:

1. Using 3rd party controller apps that emulate other controllers (I'm actually using it with my DS4 controller because it makes it possible to use higher pooling rates which means lower latency)
2. Using controllers that are not Sony licensed or an Xbox controller and want PS prompts

After i disabled DS4 Windows it let me show PS buttons but there might be other reasons as to why it could not work for others so i think having an option to force one over the other whatever controller you have is a great addition to the game, thanks for the implementation!

**Comment by GamerzHell9137** [comment]
I've got a slight nitpick tho. From the image above seems like numbered controls are there too in the game files. Any way to enable them too? Its for those random knockoff Chinese controllers. Hardly think anyone will use but if there's a way to enable them i wouldn't be opposed for the option for those individuals who want to use the numbers for some reason lol

**Comment by GamerzHell9137** [comment]
Also PC prompts are disabled when you force one of them so an option for PC propts only would be nice too.

**Comment by Lyall** [comment]
> I've got a slight nitpick tho. From the image above seems like numbered controls are there too in the game files. Any way to enable them too? Its for those random knockoff Chinese controllers. Hardly think anyone will use but if there's a way to enable them i wouldn't be opposed for the option for those individuals who want to use the numbers for some reason lol

I've tried every controller "type" the game offers and none of them seem to use the generic gamepad glyphs. It's likely that they're just leftovers and unused. 

> Also PC prompts are disabled when you force one of them so an option for PC propts only would be nice too.

Keyboard glyphs are loaded in a different way using a different texture atlas so if you want working keyboard glyphs then you just need to disable the controller icon override.

**Comment by GamerzHell9137** [comment]
> > I've got a slight nitpick tho. From the image above seems like numbered controls are there too in the game files. Any way to enable them too? Its for those random knockoff Chinese controllers. Hardly think anyone will use but if there's a way to enable them i wouldn't be opposed for the option for those individuals who want to use the numbers for some reason lol
> 
> I've tried every controller "type" the game offers and none of them seem to use the generic gamepad glyphs. It's likely that they're just leftovers and unused.
> 
> > Also PC prompts are disabled when you force one of them so an option for PC propts only would be nice too.
> 
> Keyboard glyphs are loaded in a different way using a different texture atlas so if you want working keyboard glyphs then you just need to disable the controller icon override.

Isn't ``RF5SteamInput.SteamInputManager.ControllerType.Default`` the default aka PC prompts? Can't that be set as PC in the values for controller type in the config file?

**Comment by Algester** [comment]
> I don't know if this is helpful: To my surprise my game was using Playstation button prompts from the beginning.
> 
> I'm using a "Thrustmaster ESWAP PRO for PS4 and PC" Controller and when I open the "Controller Configuration" from within the Steam Overlay it shows a picture of a PS4 controller. So if Steam thinks that you're using a PS4 controller it seems the game will automatically use PS button prompts.

this is game by game basis mind you not all games are parsing through steamapi
