### ISSUE TITLE
Can't get it to work on Steam Deck?

### ISSUE THREAD

**Issue by Xbob42** [Lyall/RF5Fix#2]
Managed it just fine on my PC, looks and plays excellently! On my Deck, however, no go. I'm worried it may not be compatible with this mod to see controller icons on the Deck: https://steamcommunity.com/sharedfiles/filedetails/?id=2834887759 (I reverted back to the normal Rune Factory 5.exe and steam_api64.ll but it still didn't work... and strangely, still had proper controller icons, so I'm unsure...)

I don't know if that's the issue, or if this fix just can't be applied to the Deck, and I'm not sure where else to ask! After unzipping the files to the game's folder on my Deck, it launches and plays just fine, but nothing is changed.

**Comment by KingKrouch** [comment]
Try using `WINEDLLOVERRIDE="winhttp=n,b" %command%` in the launch parameters of the game.

**Comment by Xbob42** [comment]
Thanks for the quick reply! Unfortunately this doesn't seem to have made a difference, unless I did it wrong?
![XaJNf4g](https://user-images.githubusercontent.com/100549231/179366558-cb40eeaa-8e0a-478d-9e1d-cece57dae8e9.png)

After opening the game, the BepInEx folder doesn't populate like it does on my PC.

**Comment by KingKrouch** [comment]
> Thanks for the quick reply! Unfortunately this doesn't seem to have made a difference, unless I did it wrong?
> 
> ![XaJNf4g](https://user-images.githubusercontent.com/100549231/179366558-cb40eeaa-8e0a-478d-9e1d-cece57dae8e9.png)
> 
> 
> 
> After opening the game, the BepInEx folder doesn't populate like it does on my PC.

I sent out my Steam Deck for an RMA about a week ago, so I'm unfortunately unable to test this unless I whip out my PopOS LiveUSB (which should have enough space for running the game in a prefix at least). That will have to wait until I get some Python scripting work that I have due finished though.

**Comment by Xbob42** [comment]
No problem, I appreciate the replies! I'll keep a patient eye out and probably stick mostly to the PC version for now, the smooth camera movement is just so nice -- camera judders drive me mad.

Oh! This is unrelated and beyond the scope of this mod, so feel free to ignore it since I don't want to waste your time and it's not your problem to fix: but part of this game's Steam Cloud functionality appears to upload your config; this is cumbersome when switching between the Deck and my PC, as one is 1280 x 800 and the other is 4k, requiring me to switch resolutions manually each time. Any known way to get it to not upload certain files to the Steam Cloud?

Being able to jump between the two platforms is awesome, fiddling with settings every time less so, and given the general quality of the port I don't expect many forthcoming developer answers.

**Comment by Azurion42** [comment]
I'm running Kubuntu 22.04, dropped this into my game folder, added that launch command KingKrouch suggested then started up my game, the performance was horrible as I started up the game, it was registering 60FPS but it felt like 15.

**Comment by Lyall** [comment]
So I've just been able to test this myself and the launch command you want is `WINEDLLOVERRIDES="winhttp=n,b" ` not `WINEDLLOVERRIDE="winhttp=n,b" `. Missing an S there. Seems to work fine on the deck after that. I'll be adding some modifications that are relevant for the steam deck shortly. At the moment the mod doesn't remove letterboxing, only pillarboxing which poses an issue at narrower than 16:9 aspects.

**Comment by Xbob42** [comment]
That worked perfectly, thanks! Can't wait for those Deck-relevant modifications, gonna be good!

**Comment by Lyall** [comment]
[The latest release](https://github.com/Lyall/RF5Fix/releases) should sort out letterboxing and screen fading on the Steam Deck and narrow than 16:9 aspects. I've also added some instructions on how to get the mod working with Linux/SteamOS. 

Let me know what you think and if anything else should be addressed for the deck in particular.

**Comment by Lyall** [comment]
> Oh! This is unrelated and beyond the scope of this mod, so feel free to ignore it since I don't want to waste your time and it's not your problem to fix: but part of this game's Steam Cloud functionality appears to upload your config; this is cumbersome when switching between the Deck and my PC, as one is 1280 x 800 and the other is 4k, requiring me to switch resolutions manually each time. Any known way to get it to not upload certain files to the Steam Cloud?

I don't think there is a way to manually exclude files from Steam Cloud unless the developer chooses too. You can see what they've set for this on [SteamDB](https://steamdb.info/app/1702330/ufs/). In Rune Factory 5's case it's just the whole save folder.

**Comment by Xbob42** [comment]
Few days late but thanks, it all works sublimely now!
