### ISSUE TITLE
unity base libraries fail to download

### ISSUE THREAD

**Issue by bobg9** [Lyall/RF5Fix#27]
getting the below error when running:
[Message:InteropManager] Downloading unity base libraries
[Error  :InteropManager] Failed to generate Il2Cpp interop assemblies: System.Net.Http.HttpRequestException: Response status code does not indicate success: 522 ().
it looks like "https://unity.bepinex.dev" is indeed not working, did the URL change or is this a temporary issue?

**Comment by Lyall** [comment]
It seems to be down for me. Likely just a temporary issue.

![image](https://github.com/user-attachments/assets/326d273c-ed38-4563-86ad-64a60f94a72e)

**Comment by bobg9** [comment]
thanks for confirming this is the URL and it should work, closing the issue
