### ISSUE TITLE
Can you add 16:10 Ratio?

### ISSUE THREAD

**Issue by Jazzneo** [Lyall/RF5Fix#3]
Can you add 16:10 Ratio? So it fit whole steam deck screen?

**Comment by Lyall** [comment]
I just got my hands on steam deck so I'll be adding letterbox removal and making sure it works properly soon.

**Comment by Lyall** [comment]
The latest release should address UI scaling and letterboxing at narrower than 16:9 aspect ratios such as the resolution the Steam Deck uses.

**Comment by Lyall** [comment]
Going to close this issue now and refer people to this issue (#2) for issues pertaining to the Steam Deck.
