### ISSUE TITLE
Custom Resolution added back

### ISSUE THREAD

**Issue by Spike2D** [Lyall/RF5Fix#5]
I'm stuck using your older version since I was using it for the custom resolution solution, it would be awesome if you could bring it back into the newer versions.

**Comment by Lyall** [comment]
I can totally add it back in the next release. I only removed it as it seemed unnecessary given the launcher doesn't use restricted resolutions.

**Comment by Lyall** [comment]
That should be it back and better than ever in v0.0.9 

If you enable it in the config it will override any resolution/window mode you have set in the launcher. Let me know how it goes for you!

**Comment by Spike2D** [comment]
Working perfectly, thanks a bunch Lyall 👍
